Move set -e after pylint call

diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-set -e
 
 ERRORS_THRESHOLD=0
 WARNINGS_THRESHOLD=10
@@ -8,8 +7,15 @@ WARNINGS_THRESHOLD=10
 
 OUT=$(pylint ./sculpt)
 
+set -e
+
 PYLINT_ERRORS=$(printf $OUT | grep '\[E' | wc -l)
 PYLINT_WARNINGS=$(printf "$OUT" | grep '\[W' | wc -l)
+
+
+echo "$OUT"
+echo "errors_count=$PYLINT_ERRORS"
+echo "warnings_count=$PYLINT_WARNINGS"
 
 if [[ $PYLINT_ERRORS -gt $ERRORS_THRESHOLD ]]; then
     echo "Pylint issues exceeded number of errors ($PYLINT_ERRORS > $ERRORS_THRESHOLD)"
@@ -20,7 +26,3 @@ if [[ $PYLINT_WARNINGS -gt $WARNINGS_THRESHOLD ]]; then
     echo "Pylint issues exceeded number of errors ($PYLINT_ERRORS > $WARNINGS_THRESHOLD)"
     exit 1
 fi
-
-echo "$OUT"
-echo "errors_count=$PYLINT_ERRORS"
-echo "warnings_count=$PYLINT_WARNINGS"
